swagger: "2.0"
info:
  title: Mikes demo
  description: Demo api gateway
  version: 1.0.0
x-google-backend:
  address: ${backend_address}
schemes:
  - https
paths:
  /weather:
    post:
      tags:
        - Weather
      description: forecast
      operationId: WeatherForecast
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/WeatherForecast"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: Success response
          schema:
            type: string
        500:
          description: Failed to load the record
          schema:
            type: string

definitions:
  WeatherForecast:
    type: object
    properties:
      id:
        type: string
      time:
        type: string
      barcode:
        type: string
      alertid:
        type: integer
      status:
        type: string
      user:
        type: string
  DeleteDeviceType:
    type: object
    properties:
      id:
        type: string
      time:
        type: string
      barcode:
        type: string
      user:
        type: string

security:
  - api_key: [ ]
    google_jwt: [ ]
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
  google_jwt:
    authorizationUrl: ''
    flow: implicit
    type: oauth2
    x-google-issuer: demo-app-client@${project_name}.iam.gserviceaccount.com
    x-google-audiences: ${project_name}
    x-google-jwks_uri: >-
      https://www.googleapis.com/service_accounts/v1/jwk/mikes-demo@${project_name}.iam.gserviceaccount.com